<?php
  /**
   *
   *
   * Social Icons options
   *
   * @package Lucent
   **/

  Redux::setSection(
	  'lucent_opts',
	  array(
		  'id'         => 'social_icons',
		  'title'      => __( 'Social Icons','lucent' ),
		  'subtitle' => __( 'Don\'t forget http://' , 'lucent' ),
		  'desc'     => __( '<strong>Don\'t forget http://<strong>','lucent' ),
		  'icon'       => 'panel-target',
		  'subsection' => true,
		  'fields'       => array(
			  array(
				  'id'        => 'lucent_facebook_url',
				  'type'      => 'text',
				  'title'     => __( 'Facebook', 'lucent' ),
				  'desc'  => __( 'Please enter Facebook page URL.', 'lucent' ),
				  'validate'  => 'url',
				  'default'   => '',
			  ),
			  array(
				  'id'        => 'lucent_twitter_url',
				  'type'      => 'text',
				  'title'     => __( 'Twitter', 'lucent' ),
				  'desc'    => __( 'Please enter twitter URL.', 'lucent' ),
				  'validate'  => 'url',
				  'default'   => '',
			  ),
			  array(
				  'id'        => 'lucent_flickr_url',
				  'type'      => 'text',
				  'title'     => __( 'Flickr', 'lucent' ),
				  'desc'  => __( 'Please enter Flickr URL.', 'lucent' ),
				  'validate'  => 'url',
				  'default'   => '',
			  ),
			  array(
				  'id'        => 'lucent_googleplus_url',
				  'type'      => 'text',
				  'title'     => __( 'Google+', 'lucent' ),
				  'desc'  => __( 'Please enter Google+ URL.', 'lucent' ),
				  'validate'  => 'url',
				  'default'   => '',
			  ),
			  array(
				  'id'        => 'lucent_pinterest_url',
				  'type'      => 'text',
				  'title'     => __( 'Pinterest', 'lucent' ),
				  'desc'  => __( 'Please enter Pinterest URL.', 'lucent' ),
				  'validate'  => 'url',
				  'default'   => '',
			  ),
			  array(
				  'id'        => 'lucent_instagram_url',
				  'type'      => 'text',
				  'title'     => __( 'Instagram', 'lucent' ),
				  'desc'  => __( 'Please enter Instagram URL.', 'lucent' ),
				  'validate'  => 'url',
				  'default'   => '',
			  ),
			  array(
				  'id'        => 'lucent_tumblr_url',
				  'type'      => 'text',
				  'title'     => __( 'Tumblr', 'lucent' ),
				  'desc'  => __( 'Please enter Tumblr URL.', 'lucent' ),
				  'validate'  => 'url',
				  'default'   => '',
			  ),
			  array(
				  'id'        => 'lucent_blogger_url',
				  'type'      => 'text',
				  'title'     => __( 'Blogger', 'lucent' ),
				  'desc'  => __( 'Please enter Blogger URL.', 'lucent' ),
				  'validate'  => 'url',
				  'default'   => '',
			  ),
			  array(
				  'id'        => 'lucent_youtube_url',
				  'type'      => 'text',
				  'title'     => __( 'Youtube', 'lucent' ),
				  'desc'    => __( 'Please enter youtube channel URL.', 'lucent' ),
				  'validate'  => 'url',
				  'default'   => '',
			  ),
			  array(
				  'id'        => 'lucent_vimeo_url',
				  'type'      => 'text',
				  'title'     => __( 'Vimeo', 'lucent' ),
				  'desc'  => __( 'Please enter Vimeo URL.', 'lucent' ),
				  'validate'  => 'url',
				  'default'   => '',
			  ),
			  array(
				  'id'        => 'lucent_github_url',
				  'type'      => 'text',
				  'title'     => __( 'Github', 'lucent' ),
				  'desc'  => __( 'Please enter github URL.', 'lucent' ),
				  'validate'  => 'url',
				  'default'   => '',
			  ),
			  array(
				  'id'        => 'lucent_linkedin_url',
				  'type'      => 'text',
				  'title'     => __( 'Linked in', 'lucent' ),
				  'desc'  => __( 'Please enter Pinterest URL.', 'lucent' ),
				  'validate'  => 'url',
				  'default'   => '',
			  ),
			  array(
				  'id'        => 'lucent_vine_url',
				  'type'      => 'text',
				  'title'     => __( 'Vine', 'lucent' ),
				  'desc'  => __( 'Please enter Vine URL.', 'lucent' ),
				  'validate'  => 'url',
				  'default'   => '',
			  ),
			  array(
				  'id'        => 'lucent_slideshare_url',
				  'type'      => 'text',
				  'title'     => __( 'Slideshare', 'lucent' ),
				  'desc'  => __( 'Please enter slideshare URL.', 'lucent' ),
				  'validate'  => 'url',
				  'default'   => '',
			  ),
			  array(
				  'id'        => 'lucent_vk_url',
				  'type'      => 'text',
				  'title'     => __( 'Vk', 'lucent' ),
				  'desc'    => __( 'Please enter Vk URL.', 'lucent' ),
				  'validate'  => 'url',
				  'default'   => '',
			  ),
			  array(
				  'id'        => 'lucent_soundcloud_url',
				  'type'      => 'text',
				  'title'     => __( 'Soundcloud', 'lucent' ),
				  'desc'  => __( 'Please enter Soundcloud page URL.', 'lucent' ),
				  'validate'  => 'url',
				  'default'   => '',
			  ),
			  array(
				  'id'        => 'lucent_skype_url',
				  'type'      => 'text',
				  'title'     => __( 'Skype', 'lucent' ),
				  'desc'  => __( 'Please enter Skype ID.', 'lucent' ),
				  'validate'  => 'url',
				  'default'   => '',
			  ),
			  array(
				  'id'        => 'lucent_dropbox_url',
				  'type'      => 'text',
				  'title'     => __( 'Dropbox', 'lucent' ),
				  'desc'  => __( 'Please enter Dropbox URL.', 'lucent' ),
				  'validate'  => 'url',
				  'default'   => '',
			  ),
			  array(
				  'id'        => 'lucent_forrst_url',
				  'type'      => 'text',
				  'title'     => __( 'Forrst', 'lucent' ),
				  'desc'  => __( 'Please enter Forrst URL.', 'lucent' ),
				  'validate'  => 'url',
				  'default'   => '',
			  ),

			  array(
				  'id'        => 'lucent_yahoo_url',
				  'type'      => 'text',
				  'title'     => __( 'Yahoo', 'lucent' ),
				  'desc'  => __( 'Please enter Yahoo URL.', 'lucent' ),
				  'validate'  => 'url',
				  'default'   => '',
			  ),
			  array(
				  'id'        => 'lucent_delicious_url',
				  'type'      => 'text',
				  'title'     => __( 'Delicious', 'lucent' ),
				  'desc'    => __( 'Please enter Delicious URL.', 'lucent' ),
				  'validate'  => 'url',
				  'default'   => '',
			  ),
			  array(
				  'id'        => 'lucent_xing_url',
				  'type'      => 'text',
				  'title'     => __( 'Xing', 'lucent' ),
				  'desc'  => __( 'Please enter Xing URL.', 'lucent' ),
				  'validate'  => 'url',
				  'default'   => '',
			  ),
			  array(
				  'id'        => 'lucent_paypal_url',
				  'type'      => 'text',
				  'title'     => __( 'Paypal', 'lucent' ),
				  'desc'  => __( 'Please enter Paypal URL.', 'lucent' ),
				  'validate'  => 'url',
				  'default'   => '',
			  ),
			  array(
				  'id'        => 'lucent_foursquare_url',
				  'type'      => 'text',
				  'title'     => __( 'Foursqaure', 'lucent' ),
				  'desc'  => __( 'Please enter Foursquare URL.', 'lucent' ),
				  'validate'  => 'url',
				  'default'   => '',
			  ),
			  array(
				  'id'        => 'lucent_email_url',
				  'type'      => 'text',
				  'title'     => __( 'Email', 'lucent' ),
				  'desc'  => __( 'Please enter Email address.', 'lucent' ),
				  'validate'  => 'email',
				  'default'   => '',
			  ),

		  ),
	  )
  );
